---
kind: Service
apiVersion: v1
metadata:
  name: satellite
  namespace: openshift-vms
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: katello
      protocol: TCP
      port: 5646
      targetPort: 5646
    - name: puppet
      protocol: TCP
      port: 8140
      targetPort: 8140
    - name: hostregistration
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: api
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    kubevirt.io/domain: satellite