apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: bm1-f7g6q-worker-0
  namespace: openshift-machine-api
  labels:
    app.kubernetes.io/instance: scaleupcluster
    machine.openshift.io/cluster-api-cluster: bm1-f7g6q
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 5
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: bm1-f7g6q
      machine.openshift.io/cluster-api-machineset: bm1-f7g6q-worker-0
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: bm1-f7g6q
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: bm1-f7g6q-worker-0
    spec:
      metadata: {}
      providerSpec:
        value:
          apiVersion: baremetal.cluster.k8s.io/v1alpha1
          hostSelector: {}
          image:
            checksum: >-
              http://10.6.81.3:6180/images/rhcos-48.84.202106091622-0-openstack.x86_64.qcow2/cached-rhcos-48.84.202106091622-0-openstack.x86_64.qcow2.md5sum
            url: >-
              http://10.6.81.3:6180/images/rhcos-48.84.202106091622-0-openstack.x86_64.qcow2/cached-rhcos-48.84.202106091622-0-openstack.x86_64.qcow2
          kind: BareMetalMachineProviderSpec
          metadata: {}
          userData:
            name: worker-user-data