
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    description: aap-exec2
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    name.os.template.kubevirt.io/rhel8.4: Red Hat Enterprise Linux 8.0 or higher
  name: aap-exec2
  namespace: openshift-vms
  labels:
    app: aap-exec2
    os.template.kubevirt.io/rhel8.4: 'true'
    vm.kubevirt.io/template: rhel8-server-large
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.15.1
    workload.template.kubevirt.io/server: 'true'
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: aap-exec2-rootdisk-bm99l
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 60Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Block
        source:
          pvc:
            name: rhel8
            namespace: openshift-virtualization-os-images
    - metadata:
        creationTimestamp: null
        name: aap-exec2-datadisk-za02m
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 40Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Block
        source:
          blank: {}
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: large
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: aap-exec2
        kubevirt.io/size: large
        os.template.kubevirt.io/rhel8.4: 'true'
        vm.kubevirt.io/name: aap-exec2
        workload.template.kubevirt.io/server: 'true'
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              configDrive: {}
            source:
              secret:
                secretName: sshkey
      domain:
        cpu:
          cores: 2
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: datadisk
          interfaces:
            - macAddress: ''
              masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 16Gi
      evictionStrategy: LiveMigrate
      hostname: aap-exec2
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              user: cloud-user
              password: nfd8-r23e-57y5
              chpasswd: { expire: False }
          name: cloudinitdisk
        - dataVolume:
            name: aap-exec2-rootdisk-bm99l
          name: rootdisk
        - dataVolume:
            name: aap-exec2-datadisk-za02m
          name: datadisk

---
kind: Service
apiVersion: v1
metadata:
  name: aap-exec2-ssh
  namespace: openshift-vms
spec:
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22
  selector:
    kubevirt.io/domain: aap-exec2

---
kind: Service
apiVersion: v1
metadata:
  name: aap-exec2-service
  namespace: openshift-vms
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    kubevirt.io/domain: aap-exec2
