apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    description: vm4
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    name.os.template.kubevirt.io/rhel8.4: Red Hat Enterprise Linux 8.0 or higher
  name: vm4
  namespace: openshift-vms
  labels:
    app: vm4
    os.template.kubevirt.io/rhel8.4: 'true'
    vm.kubevirt.io/template: rhel8-server-large
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.15.1
    workload.template.kubevirt.io/server: 'true'
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: vm4-rootdisk-bm99l
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 40Gi
          storageClassName: ocs-storagecluster-ceph-rbd
          volumeMode: Block
        source:
          pvc:
            name: rhel8
            namespace: openshift-virtualization-os-images
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: large
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: vm4
        kubevirt.io/size: large
        os.template.kubevirt.io/rhel8.4: 'true'
        vm.kubevirt.io/name: aap-controller
        workload.template.kubevirt.io/server: 'true'
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              configDrive: {}
            source:
              secret:
                secretName: authorizedsshkeys
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - macAddress: ''
              masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      hostname: vm4
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              user: cloud-user
              password: nfd8-r23e-57y5
              chpasswd: { expire: False }
          name: cloudinitdisk
        - dataVolume:
            name: vm4-rootdisk-bm99l
          name: rootdisk
